"Entidades que participan en el cumplimiento de recomendaciones AGA": 
  - "Entidades responsables"
  - percentage_of
  - percentage
"Proceso de evaluación AGA":
  - nombre_compromiso
  - completitud
"Cronograma de actividades por compromiso":
  - nombre_compromiso
  - actividad
  - fecha_inicio
  - fecha_fin
  - completitud